apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: hostpath
  hostPath:
    path: /mysql


--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-hostpath
  # storageClassName: standard