apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: hostpath
  hostPath:
    path: /run/desktop/mnt/host/d/Project/mysql


--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-hostpath
  # storageClassName: standard