apiVersion: v1
kind: Secret
metadata:
  name: mysqldetails
  namespace: database
type: Opaque
data:
  MYSQL_PASSWORD: cGFzc3dvcmQ= #password
  MYSQL_USER: dXNlcg== #user
  MYSQL_ROOT_PASSWORD: bXlzZWNyZXRwYXNzd29yZA== #mysecretpassword
  MYSQL_DATABASE: cG9zdHM= #posts

---

apiVersion: v1
kind: Secret
metadata:
  name: mysqldetails
  namespace: backend
type: Opaque
data:
  MYSQL_PASSWORD: cGFzc3dvcmQ= #password
  MYSQL_USER: dXNlcg== #user
  MYSQL_DB: cG9zdHM= #posts
