apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      # securityContext:
      #   fsGroup: 1000
      volumes:
        - name: vol-jenkins
          persistentVolumeClaim:
            claimName: pvc-jenkins
        # - name: kubectl-bin
        #   hostPath:
        #     path: "/run/desktop/mnt/host/c/Program Files/Docker/Docker/resources/bin/kubectl"
        #     # type: File
      containers:
      - name: jenkins
        
        securityContext:
          # runAsGroup: 1000
          runAsUser: 0
        image: jenkins/jenkins
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
            chmod +x kubectl && \
            mv kubectl /usr/bin/ && \
            exec /usr/bin/tini -- /usr/local/bin/jenkins.sh  # Start Jenkins after installing kubectl
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: vol-jenkins
          mountPath: /var/jenkins_home
        # - name: kubectl-bin
        #   mountPath: /usr/local/bin/kubectl
        #   subPath: kubectl
        ports:
        - containerPort: 8080
        - containerPort: 50000


---

apiVersion: v1 
kind: Service
metadata: 
  name: svc-jenkins
  namespace: jenkins
spec:
  type: ClusterIP 
  selector:
    app: jenkins
  ports:
  - port: 8080
    name: ui
    targetPort: 8080
  - port: 50000
    name: worker
    targetPort: 50000