apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /hostpath-jenkins
  storageClassName: hostpath

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins
  namespace: jenkins
spec:
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-jenkins
  accessModes:
    - ReadWriteMany
